
@baseUrl = {{$local}}


### Sing UP -----------------------
POST {{baseUrl}}/users/signup
content-type: application/json

{
  "name": "Gleyson Carvalho",
  "email": "gleysonpc@gmail.com",
  "password": "123456"
}

### Login -----------------------
# @name loginApi
POST {{baseUrl}}/users/login
content-type: application/json

{
  "email": "gleysonpc@gmail.com",
  "password": "123456"
}

### List Users -----------------------
GET {{baseUrl}}/users
content-type: application/json
Authorization: Bearer {{loginApi.response.body.accessToken}}

### Show User -----------------------
GET {{baseUrl}}/users/ae974b1b-f470-41ef-b27c-85f5f9d5696f
content-type: application/json
Authorization: Bearer {{loginApi.response.body.accessToken}}

### Create User -----------------------
POST {{baseUrl}}/users
content-type: application/json
Authorization: Bearer {{loginApi.response.body.accessToken}}

{
    "name": "Deelan"
}

### Create Balance -----------------------
POST {{baseUrl}}/balances
content-type: application/json
Authorization: Bearer {{loginApi.response.body.accessToken}}

{
    "description": "Mes de Julho"
}

### List User Balances -----------------------
GET {{baseUrl}}/balances
content-type: application/json
Authorization: Bearer {{loginApi.response.body.accessToken}}

### Create Earning -----------------------
POST {{baseUrl}}/balances/b5cc4c44-0509-4b84-9b26-d6a5f0c6c509/earnings
content-type: application/json
Authorization: Bearer {{loginApi.response.body.accessToken}}

{
    "description": "Salario febracis",
    "amount": 3500.00
}

### List Earnings -----------------------
GET  {{baseUrl}}/balances/b5cc4c44-0509-4b84-9b26-d6a5f0c6c509/earnings
content-type: application/json
Authorization: Bearer {{loginApi.response.body.accessToken}}


