service: xpay-backend
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-typescript


provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    USERS_TABLE_NAME: ${self:custom.UsersTable.name}
  iamRoleStatements:
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}

resources:
  Resources:
    UsersTable: ${file(resources/XpayUsersTable.yml):UsersTable}

functions:
  api:
    handler: src/main.handler
    events:
      - http:
          path: '/{proxy+}'
          method: ANY
      # - httpApi: '*'

custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
