UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: XpayUsersTable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userByEmail
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
                ProjectionType: ALL
